name: e_fu
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+0

environment:
  sdk: '>=2.19.0-215.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.20.1
  shared_preferences:
  flutter_easyloading:
  crypto: ^3.0.3
  http: ^0.13.5
  age_calculator: ^1.0.0
  ele_progress: ^0.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.0
  logger: ^1.3.0
  flutter_ringtone_player: ^3.2.0
  fl_chart: ^0.62.0
  flutter_spinkit: ^5.2.0
  flutter_local_notifications:
  
  js: ^0.6.5
  fluttertoast: ^8.2.2
  jiffy: ^6.2.1
  cupertino_icons: ^1.0.0
  auto_size_text:
  collection: ^1.17.2
  mqtt_client: ^10.0.1

  


dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: taipei
      fonts:
        - asset: assets/font/jf-openhuninn-1.1.ttf
  assets:
      - assets/images/
      
